# Generated by Django 5.1.6 on 2025-03-03 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=40)),
                ('frame_type', models.CharField(default='monster', max_length=40)),
                ('effect', models.TextField()),
                ('attack', models.IntegerField(null=True)),
                ('defense', models.IntegerField(null=True)),
                ('level_rank', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('spell_trap_race', models.CharField(max_length=30, null=True)),
                ('monster_race', models.CharField(max_length=30, null=True)),
                ('attribute', models.CharField(max_length=10, null=True)),
                ('archetype', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='card_images/default.jpg', upload_to='card_images/')),
            ],
        ),
    ]
