# Generated by Django 5.1.6 on 2025-03-03 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='attribute',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='frame_type',
            field=models.CharField(db_index=True, default='monster', max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='level_rank',
            field=models.IntegerField(db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='monster_race',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='spell_trap_race',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
