# Generated by Django 5.1.6 on 2025-03-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_deckcard_deck_cards_extradeckcard_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together={('deck', 'card')},
        ),
        migrations.AlterUniqueTogether(
            name='extradeckcard',
            unique_together={('deck', 'card')},
        ),
    ]
